version: '3.0'
services:
  postgres_db:
    container_name: 'postgres_db'
    image: postgres:14.7-alpine
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    networks:
      - custom

  postgres_db_test:
    container_name: 'postgres_db_test'
    image: postgres:14.7-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME_TEST}
      POSTGRES_USER: ${DB_USER_TEST}
      POSTGRES_PASSWORD: ${DB_PASS_TEST}
    ports:
      - ${DB_PORT_TEST}:5432
    networks:
      - custom

  redis:
    container_name: 'redis'
    image: redis:alpine
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - custom

networks:
  custom:
    driver: bridge