version: '3.0'
services:
  postgres_db:
    container_name: 'postgres_db'
    image: postgres:14.7-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - custom

networks:
  custom:
    driver: bridge